Repository SilviaPabon/AUTO-UPB, pull requests merged in 2022-02, with the labels that each got.

#90 Variables y componentes iniciales de SASS.
  src/public/styles/base/_globals.scss
  src/public/styles/components/.gitkeep
  src/public/styles/components/_components.scss
  src/public/styles/main.scss
Labels: good first issue

#92 SCRIPTS INICIALES PARA LA BASE DE DATOS
  src/database/SQL/query_db_pi.sql
  src/database/SQL/query_inserts.sql
  src/database/SQL/query_procedures.sql
  src/database/SQL/query_triggers.sql
  src/database/creation_script.sql
Labels: good first issue

#93 Login&signup
  .eslintrc.json
  .gitignore
  src/controllers/.gitkeep
  src/controllers/controller_auth.js
  src/controllers/general_routes.js
  src/database/SQL/query_db_pi.sql
  src/database/SQL/query_inserts.sql
  src/database/SQL/query_procedures.sql
  src/database/connection.js
  src/index.js
  src/libs/.gitkeep
  src/libs/helpers.js
  src/libs/passport.js
  src/public/scripts/.gitkeep
  src/public/scripts/alerts.js
  src/public/scripts/login_validate.js
  src/public/scripts/navbar.js
  src/public/scripts/signup_validate.js
  src/public/styles/_mediaQueries.scss
  src/public/styles/components/_components.scss
  src/public/styles/layouts/.gitkeep
  src/public/styles/layouts/_nav.scss
  src/public/styles/main.css
  src/public/styles/main.scss
  src/public/styles/pages/.gitkeep
  src/public/styles/pages/_signup.scss
  src/routes/general_routes.js
  src/routes/router.js
  src/routes/router_authentication.js
  src/routes/users.js
  src/views/auth/login.ejs
  src/views/auth/signup.ejs
  src/views/partials/.gitkeep
  src/views/partials/_globalScripts.ejs
  src/views/partials/_messages.ejs
  src/views/partials/_navbar.ejs
Labels: User story completed 📖, Activity completed 📄

#94 Nav roles
  src/controllers/controller_auth.js
  src/controllers/general_routes.js
  src/database/SQL/query_db_pi.sql
  src/database/SQL/query_procedures.sql
  src/index.js
  src/public/scripts/login_validate.js
  src/public/scripts/signup_validate.js
  src/public/styles/_mediaQueries.scss
  src/public/styles/layouts/_nav.scss
  src/public/styles/main.css
  src/routes/router_authentication.js
  src/views/partials/_navbar.ejs
Labels: enhancement

#95 Manual de Respaldo
  docs/Enlaces a documentos y manuales internos.txt
Labels: documentation, User story completed 📖, Activity completed 📄

#97 Interfaces y validación de creación de cuentas por Admin
  src/controllers/admin_controller.js
  src/database/SQL/query_procedures.sql
  src/index.js
  src/libs/passport.js
  src/public/scripts/signup_admin_validate.js
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/routes/admin.js
  src/routes/router.js
  src/views/auth/create_acc_admin.ejs
Labels: User story completed 📖, Activity completed 📄, SPRINT 1

#96 Accessories inventory front
  src/controllers/admin_controller.js
  src/public/images/.gitkeep
  src/public/images/Asiento_grande_para_niños.jpg
  src/public/images/Asiento_mediano_para_niños.jpg
  src/public/images/Asiento_pequeño_para_bebé.jpg
  src/public/images/Cubierta_gris_para_carro.jpg
  src/public/images/Cubierta_negra_para_carro.jpg
  src/public/images/Dados_decorativos_para_interior.jpg
  src/public/images/Funda_de_cuero_azul_para_volante.jpg
  src/public/images/Funda_de_tela_para_volante.jpg
  src/public/images/Funda_negra_para_volante.jpg
  src/public/images/Rin_cromado_dorado_16in.jpg
  src/public/images/Rin_cromado_dorado_24in.jpg
  src/public/images/Rin_cromado_plateado_18in.jpg
  src/public/images/Rin_cromado_plateado_24in.jpg
  src/public/images/Rin_cromado_plateado_26in.jpg
  src/public/images/inventory_existing_accessory.jpg
  src/public/images/inventory_new_accessory.jpg
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/public/styles/main.scss
  src/public/styles/pages/_inventory_select_accessory_type.scss
  src/public/styles/pages/_inventory_select_existing_accessory.scss
  src/routes/admin.js
  src/routes/router.js
  src/views/admin/existing_accessory.ejs
  src/views/admin/inventory_select_accessory_type.ejs
  src/views/admin/inventory_select_existing_accessory.ejs
  src/views/admin/new_accessory.ejs
  src/views/auth/login.ejs
  src/views/auth/signup.ejs
  src/views/partials/_globalHeaders.ejs
  src/views/partials/_navbar.ejs
Labels: Activity completed 📄

#98 Update database scripts
  src/database/SQL/query_db_pi.sql
  src/database/SQL/query_inserts.sql
  src/database/SQL/query_procedures.sql
  src/database/SQL/query_triggers.sql
Labels: enhancement

#109 link del manual de politica de proteccion de datos
  docs/Enlaces a documentos y manuales internos.txt
  src/views/auth/create_acc_admin.ejs
  src/views/auth/signup.ejs
Labels: Activity completed 📄
