Repository SilviaPabon/AUTO-UPB, pull requests merged in 2022-03, with the labels that each got.

#108 Offered accessories
  src/controllers/general_routes.js
  src/public/styles/base/_globals.scss
  src/public/styles/main.css
  src/public/styles/main.scss
  src/public/styles/pages/_products.scss
  src/routes/general_routes.js
  src/views/index.ejs
  src/views/partials/_navbar.ejs
  src/views/products.ejs
Labels: Activity completed 📄, SPRINT 1

#107 Change third part dependencies
  package.json
  src/public/fonts/Roboto-Regular.ttf
  src/public/icons/bars-solid.svg
  src/public/icons/briefcase-solid.svg
  src/public/icons/comment-alt-solid.svg
  src/public/icons/dollar-sign-solid.svg
  src/public/icons/plus-square-solid.svg
  src/public/icons/shopping-cart-solid.svg
  src/public/icons/th-list-solid.svg
  src/public/icons/times-circle-solid.svg
  src/public/icons/user-circle-solid.svg
  src/public/icons/user-cog-solid.svg
  src/public/icons/users-solid.svg
  src/public/scripts/alerts.js
  src/public/styles/_mediaQueries.scss
  src/public/styles/components/_components.scss
  src/public/styles/layouts/_nav.scss
  src/public/styles/main.css
  src/public/styles/main.scss
  src/views/partials/_globalHeaders.ejs
  src/views/partials/_globalScripts.ejs
  src/views/partials/_messages.ejs
  src/views/partials/_navbar.ejs
Labels: bug 🐛, enhancement

#111 Fixes
  src/libs/passport.js
  src/public/images/inventory_existing_accessory.jpg
  src/public/images/inventory_new_accessory.jpg
  src/public/scripts/signup_admin_validate.js
  src/public/styles/_mediaQueries.scss
  src/public/styles/components/_components.scss
  src/public/styles/layouts/_nav.scss
  src/public/styles/main.css
  src/public/styles/pages/_inventory_select_accessory_type.scss
  src/views/admin/inventory_select_accessory_type.ejs
  src/views/admin/new_accessory.ejs
  src/views/auth/create_acc_admin.ejs
  src/views/auth/signup.ejs
  src/views/partials/_navbar.ejs
Labels: bug 🐛

#112 Home
  src/controllers/general_routes.js
  src/public/fonts/Roboto-Thin.ttf
  src/public/icons/hashtag-solid.svg
  src/public/icons/map-marked-solid.svg
  src/public/icons/money-bill-wave-alt-solid.svg
  src/public/icons/phone-solid.svg
  src/public/images/Dados_decorativios_para_interior.jpg
  src/public/images/about-us.jpg
  src/public/images/home_header--medium.jpg
  src/public/images/home_header.jpg
  src/public/styles/_mediaQueries.scss
  src/public/styles/base/_globals.scss
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/public/styles/main.scss
  src/public/styles/pages/_home.scss
  src/views/index.ejs
  src/views/partials/_navbar.ejs
Labels: User story completed 📖, Activity completed 📄, SPRINT 1

#113 Admin existing accounts
  src/controllers/admin_controller.js
  src/database/SQL/query_db_pi.sql
  src/database/SQL/query_procedures.sql
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/public/styles/main.scss
  src/routes/admin.js
  src/views/admin/existing_accounts.ejs
  src/views/partials/_navbar.ejs
Labels: Activity completed 📄, SPRINT 1

#117 Backend US02
  src/controllers/general_routes.js
  src/views/products.ejs
Labels: User story completed 📖, Activity completed 📄, SPRINT 1

#116 Fixes login
  src/database/SQL/query_inserts.sql
  src/database/SQL/query_procedures.sql
  src/libs/passport.js
  src/views/partials/_navbar.ejs
Labels: Improvement 📈

#123 Protección rutas 1
  src/libs/protect_middlewares.js
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/routes/admin.js
  src/routes/router_authentication.js
  src/views/auth/create_acc_admin.ejs
  src/views/auth/login.ejs
  src/views/auth/signup.ejs
  src/views/index.ejs
Labels: Improvement 📈

#124 Us23 admin search account
  src/controllers/admin_controller.js
  src/database/SQL/query_procedures.sql
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/routes/admin.js
  src/views/admin/existing_accounts.ejs
Labels: User story completed 📖, Activity completed 📄, SPRINT 2

#127 Buy cart
  package-lock.json
  src/controllers/cart_controller.js
  src/controllers/controller_auth.js
  src/controllers/general_routes.js
  src/index.js
  src/libs/protect_middlewares.js
  src/public/scripts/addToCartBtn.js
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/public/styles/main.scss
  src/public/styles/pages/_products.scss
  src/routes/cart_api.js
  src/routes/router.js
  src/views/index.ejs
  src/views/partials/_messages.ejs
  src/views/products.ejs
Labels: Activity completed 📄

#129 Us23est cuenta front
  src/controllers/admin_controller.js
  src/database/SQL/query_db_pi.sql
  src/database/SQL/query_procedures.sql
  src/public/scripts/state_form_validation.js
  src/routes/admin.js
  src/views/admin/existing_accounts.ejs
  src/views/admin/existing_accounts_state.ejs
  src/views/partials/_stateAccount.ejs
Labels: User story completed 📖, Activity completed 📄, SPRINT 1

#128 Accessory details
  src/controllers/general_routes.js
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/public/styles/main.scss
  src/public/styles/pages/_accessory_details.scss
  src/routes/general_routes.js
  src/views/index.ejs
  src/views/productDetails.ejs
  src/views/products.ejs
Labels: User story completed 📖, Activity completed 📄, SPRINT 2

#131 General improvements
  src/public/images/Asiento_grande_para_niños.jpg
  src/public/images/Asiento_mediano_para_niños.jpg
  src/public/images/Asiento_pequeño_para_bebé.jpg
  src/public/images/Cubierta_gris_para_carro.jpg
  src/public/images/Cubierta_negra_para_carro.jpg
  src/public/images/Dados_decorativios_para_interior.jpg
  src/public/images/Funda_de_cuero_azul_para_volante.jpg
  src/public/images/Funda_de_tela_para_volante.jpg
  src/public/images/Funda_negra_para_volante.jpg
  src/public/images/Rin_cromado_dorado_16in.jpg
  src/public/images/Rin_cromado_dorado_24in.jpg
  src/public/images/Rin_cromado_plateado_18in.jpg
  src/public/images/Rin_cromado_plateado_24in.jpg
  src/public/images/Rin_cromado_plateado_26in.jpg
  src/public/images/Tapete_negro_para_carro.jpg
  src/public/images/Tapete_rojo_para_carro.jpg
  src/public/images/about-us.jpg
  src/public/images/inventory_existing_accessory.jpg
  src/public/images/inventory_new_accessory.jpg
  src/public/scripts/vendors/lazysizes.min.js
  src/views/admin/existing_accessory.ejs
  src/views/admin/inventory_select_existing_accessory.ejs
  src/views/auth/signup.ejs
  src/views/index.ejs
  src/views/partials/_globalHeaders.ejs
  src/views/partials/_navbar.ejs
  src/views/products.ejs
Labels: bug 🐛, Improvement 📈

#130 Fixes
  src/controllers/cart_controller.js
  src/controllers/general_routes.js
  src/libs/passport.js
  src/public/scripts/state_form_validation.js
  src/public/scripts/validations/inventory_add_validate.js
  src/public/scripts/validations/inventory_upd_validate.js
  src/public/scripts/validations/signup_admin_validate.js
  src/views/productDetails.ejs
Labels: bug 🐛, Improvement 📈

#134 Fix navbar z-index
  src/public/styles/layouts/_nav.scss
  src/public/styles/main.css
  src/public/styles/main.scss
Labels: bug 🐛

#133 Aria labels
  src/views/admin/existing_accounts.ejs
  src/views/admin/inventory_select_existing_accessory.ejs
  src/views/index.ejs
  src/views/productDetails.ejs
  src/views/products.ejs
Labels: Improvement 📈

#136 Update procedures
  src/controllers/admin_controller.js
  src/database/SQL/query_procedures.sql
  src/libs/passport.js
Labels: bug 🐛, Improvement 📈

#135 Protect routes
  src/routes/admin.js
  src/views/admin/inventory_select_existing_accessory.ejs
  src/views/index.ejs
  src/views/productDetails.ejs
  src/views/products.ejs
Labels: bug 🐛, Improvement 📈

#137 Fix on home
  src/views/index.ejs
Labels: bug 🐛

#140 MANAGE CART FROM DATABASE
  src/controllers/cart_controller.js
  src/controllers/controller_auth.js
  src/controllers/general_routes.js
  src/database/SQL/query_init.sql
  src/database/SQL/query_inserts.sql
  src/database/SQL/query_procedures.sql
  src/database/SQL/query_views.sql
  src/index.js
  src/public/scripts/addSub.js
  src/routes/cart_api.js
  src/views/partials/_navbar.ejs
  src/views/shop/shopping_cart.ejs
Labels: Improvement 📈

#141 US37 Frontend y backend para modificar los detalles de un accesorio
  src/controllers/admin_controller.js
  src/database/SQL/query_procedures.sql
  src/public/images/Polarizado_delantero_n70.jpg
  src/public/images/Polarizado_lateral_n55.jpg
  src/public/images/Polarizado_lateral_n70.jpg
  src/public/images/Polarizado_trasero_n14.jpg
  src/public/images/Polarizado_trasero_n35.jpg
  src/public/images/Polarizado_trasero_n50.jpg
  src/public/images/nodding_dog.jpg
  src/public/images/nodding_dog_1.jpg
  src/public/scripts/validations/inventory_upd_data_validate.js
  src/routes/admin.js
  src/views/admin/existing_accesory_modify.ejs
  src/views/admin/inventory_select_existing_accessory.ejs
  src/views/partials/_navbar.ejs
  src/views/partials/_statusAccesory.ejs
Labels: User story completed 📖, Activity completed 📄, SPRINT 2

#142 GENERACIÓN DE ORDENES DE COMPRA EN CAJA
  src/controllers/cart_controller.js
  src/controllers/employee_controller.js
  src/database/SQL/query_procedures.sql
  src/database/SQL/query_triggers.sql
  src/database/SQL/query_views.sql
  src/index.js
  src/public/scripts/addSub.js
  src/public/scripts/cart_order_search_client.js
  src/public/styles/main.css
  src/public/styles/pages/_carrito.scss
  src/routes/employee.js
  src/routes/router.js
  src/views/partials/_navbar.ejs
  src/views/shop/employee_shopping_cart.ejs
  src/views/shop/shopping_cart.ejs
Labels: User story completed 📖, Activity completed 📄, SPRINT 2

#145 Fix passport serialize
  src/libs/passport.js
Labels: bug 🐛

#143 Us11 user info update
  src/controllers/general_routes.js
  src/libs/helpers.js
  src/public/scripts/validations/update_acc_validate.js
  src/routes/general_routes.js
  src/views/partials/_navbar.ejs
  src/views/userUpdate.ejs
Labels: User story completed 📖, Activity completed 📄, SPRINT 2

#144 US-12
  src/controllers/workers_controllers.js
  src/index.js
  src/routes/router.js
  src/routes/workers.js
  src/views/workers/existing_inventory.ejs
Labels: User story completed 📖, Activity completed 📄, SPRINT 2

#147 Summarize nav
  src/public/styles/layouts/_nav.scss
  src/public/styles/main.css
  src/views/partials/_navbar.ejs
Labels: bug 🐛

#148 Fixes
  src/controllers/employee_controller.js
  src/controllers/partner_controller.js
  src/controllers/workers_controllers.js
  src/index.js
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/routes/employee.js
  src/routes/partner.js
  src/routes/router.js
  src/routes/workers.js
  src/views/admin/existing_accounts.ejs
  src/views/employees/existing_inventory.ejs
  src/views/partials/_navbar.ejs
  src/views/partner/.gitkeep
  src/views/workers/existing_inventory.ejs
Labels: bug 🐛, Improvement 📈

#150 Use express-mysql-session
  src/index.js
Labels: Improvement 📈

#149 Fix US11
  src/controllers/general_routes.js
  src/libs/passport.js
Labels: bug 🐛, SPRINT 2

#152 Hotfix de arreglos solicitados en las pruebas para SilviaPabon
  src/controllers/admin_controller.js
  src/database/SQL/query_init.sql
  src/database/SQL/query_procedures.sql
  src/views/auth/create_acc_admin.ejs
Labels: bug 🐛

#151 Tittle corrections
  docs/Enlaces a documentos y manuales internos.txt
  src/public/docs/ManualDeProteccionDatos-2022-10.pdf
  src/public/icons/favicon.ico
  src/public/images/wearcar_logo.png
  src/public/styles/_mediaQueries.scss
  src/public/styles/layouts/_nav.scss
  src/public/styles/main.css
  src/views/admin/existing_accounts.ejs
  src/views/admin/existing_accounts_state.ejs
  src/views/admin/inventory_select_existing_accessory.ejs
  src/views/auth/signup.ejs
  src/views/auth/signup_business.ejs
  src/views/partials/_globalHeaders.ejs
  src/views/partials/_navbar.ejs
  src/views/products.ejs
  src/views/shop/employee_shopping_cart.ejs
  src/views/userUpdate.ejs
Labels: bug 🐛

#155 hotfix
  src/controllers/admin_controller.js
  src/views/admin/existing_accesory_modify.ejs
Labels: bug 🐛

#154 hotfix aria
  src/views/admin/existing_accounts_state.ejs
Labels: bug 🐛

#158 visualizacion de inventario existente para los socios
  src/controllers/partner_controller.js
  src/routes/partner.js
  src/views/partials/_navbar.ejs
  src/views/partner/partners_inventory.ejs
Labels: Activity completed 📄

#157 Us7client order
  src/controllers/cart_controller.js
  src/public/scripts/addSub.js
  src/routes/cart_api.js
  src/views/clients/orders_clients.ejs
  src/views/partials/_navbar.ejs
  src/views/shop/shopping_cart.ejs
Labels: User story completed 📖, SPRINT 2

#160 Us04contact us
  src/controllers/general_routes.js
  src/public/images/contact_us.jpg
  src/public/scripts/validations/contact_us_validate.js
  src/public/styles/_mediaQueries.scss
  src/public/styles/main.css
  src/public/styles/main.scss
  src/public/styles/pages/_contactUs.scss
  src/routes/general_routes.js
  src/views/contact_us.ejs
  src/views/partials/_navbar.ejs
Labels: Activity completed 📄, SPRINT 2

#161 DEPLOY SPRINT #2
  src/controllers/admin_controller.js
  src/controllers/cart_controller.js
  src/controllers/general_routes.js
  src/controllers/partner_controller.js
  src/public/images/contact_us.jpg
  src/public/scripts/addSub.js
  src/public/scripts/validations/contact_us_validate.js
  src/public/styles/_mediaQueries.scss
  src/public/styles/main.css
  src/public/styles/main.scss
  src/public/styles/pages/_contactUs.scss
  src/routes/cart_api.js
  src/routes/general_routes.js
  src/routes/partner.js
  src/views/admin/existing_accesory_modify.ejs
  src/views/admin/existing_accounts_state.ejs
  src/views/clients/orders_clients.ejs
  src/views/contact_us.ejs
  src/views/partials/_navbar.ejs
  src/views/partner/.gitkeep
  src/views/partner/existing_accounts_partner.ejs
  src/views/partner/partners_inventory.ejs
  src/views/shop/shopping_cart.ejs
Labels: Sprint completed ☑️, SPRINT 2

#162 us-43 Update query_procedures.sql
  src/database/SQL/query_procedures.sql
Labels: Activity completed 📄, SPRINT 2

#164 Condicional y mensaje de confirmación
  src/views/shop/employee_shopping_cart.ejs
  src/views/shop/shopping_cart.ejs
Labels: bug 🐛, Improvement 📈

#165 Fixus04
  src/public/scripts/validations/contact_us_validate.js
  src/views/contact_us.ejs
Labels: bug 🐛, Improvement 📈

#181 Us08 client orders
  src/controllers/cart_controller.js
  src/controllers/user_controllers.js
  src/database/SQL/query_procedures.sql
  src/database/SQL/query_views.sql
  src/index.js
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/routes/cart_api.js
  src/routes/router.js
  src/routes/user.js
  src/views/clients/orders_clients.ejs
  src/views/partials/_navbar.ejs
Labels: User story completed 📖, Activity completed 📄, SPRINT 3

#182 Us41diagram er
  docs/diagramaER_Wearcar.mwb
  docs/diagramaER_Wearcar.png
Labels: User story completed 📖, SPRINT 2

#183 Us10 client bill
  package-lock.json
  package.json
  src/controllers/user_controllers.js
  src/database/SQL/query_init.sql
  src/database/SQL/query_procedures.sql
  src/database/SQL/query_views.sql
  src/routes/user.js
  src/views/clients/orders_clients.ejs
Labels: User story completed 📖, Activity completed 📄, SPRINT 3

#184 Fix try catch
  src/controllers/admin_controller.js
  src/controllers/general_routes.js
  src/controllers/partner_controller.js
  src/public/scripts/validations/contact_us_validate.js
  src/public/scripts/validations/signupBusiness_validaje.js
  src/public/scripts/validations/signup_admin_validate.js
  src/public/scripts/validations/signup_validate.js
  src/views/auth/create_acc_admin.ejs
  src/views/auth/signup.ejs
  src/views/auth/signup_business.ejs
  src/views/contact_us.ejs
  src/views/employees/existing_inventory.ejs
  src/views/partner/existing_accounts_partner.ejs
  src/views/partner/partners_inventory.ejs
Labels: bug 🐛, Improvement 📈

#185 Us 22
  src/controllers/admin_controller.js
  src/database/SQL/query_procedures.sql
  src/database/SQL/query_views.sql
  src/public/images/finances_financial_perform.jpg
  src/public/images/finances_historic_prices.jpg
  src/routes/admin.js
  src/views/admin/finances_historic_prices.ejs
  src/views/admin/finances_products.ejs
  src/views/admin/finances_select_option.ejs
  src/views/partials/_navbar.ejs
Labels: User story completed 📖, SPRINT 3
