Repository SilviaPabon/AUTO-UPB, pull requests merged in 2022-04, with the labels that each got.

#186 Refactors improvements
  src/public/scripts/validations/contact_us_validate.js
  src/public/scripts/validations/inventory_add_validate.js
  src/public/scripts/validations/inventory_upd_data_validate.js
  src/public/scripts/validations/inventory_upd_validate.js
  src/public/scripts/validations/login_validate.js
  src/public/scripts/validations/signupBusiness_validaje.js
  src/public/scripts/validations/signup_admin_validate.js
  src/public/scripts/validations/signup_validate.js
  src/public/scripts/validations/status_form_validation.js
  src/public/scripts/validations/update_acc_validate.js
  src/public/scripts/validations/validate_global.js
  src/public/scripts/validations/validate_global.min.js
  src/views/admin/existing_accesory_modify.ejs
  src/views/admin/existing_accessory.ejs
  src/views/admin/existing_accounts_state.ejs
  src/views/admin/new_accessory.ejs
  src/views/auth/create_acc_admin.ejs
  src/views/auth/login.ejs
  src/views/auth/signup.ejs
  src/views/auth/signup_business.ejs
  src/views/contact_us.ejs
  src/views/userUpdate.ejs
Labels: Improvement 📈

#187 Ordenes compra clientes para trabajadores
  src/controllers/employee_controller.js
  src/database/SQL/query_procedures.sql
  src/routes/employee.js
  src/views/employees/employee_show_orders.ejs
  src/views/partials/_navbar.ejs
Labels: User story completed 📖, Activity completed 📄

#189 Summarize navbar
  src/public/icons/exchange-alt-solid.svg
  src/public/styles/_mediaQueries.scss
  src/public/styles/layouts/_nav.scss
  src/public/styles/main.css
  src/public/styles/main.scss
  src/views/partials/_navbar.ejs
Labels: bug 🐛, Improvement 📈

#188 Us35show messages
  src/controllers/admin_controller.js
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/public/styles/main.scss
  src/routes/admin.js
  src/views/admin/show_messages.ejs
Labels: Activity completed 📄, SPRINT 3

#191 Hotfixes
  src/views/clients/orders_clients.ejs
  src/views/employees/employee_show_orders.ejs
  src/views/shop/employee_shopping_cart.ejs
Labels: bug 🐛, Improvement 📈

#193 Rename image on change and sanitize inputs
  src/controllers/admin_controller.js
  src/index.js
  src/public/images/Cubierta_impermeable_gris.jpg
  src/public/images/Cubierta_impermeable_negra.jpg
  src/public/images/Soporte_para_celular.jpg
  src/public/scripts/validations/validate_global.js
  src/public/scripts/validations/validate_global.min.js
  src/views/admin/existing_accesory_modify.ejs
Labels: bug 🐛, Improvement 📈

#192 Us17 open mail
  src/controllers/general_routes.js
  src/public/icons/envelope-open-text-solid.svg
  src/public/styles/layouts/_nav.scss
  src/public/styles/main.css
  src/routes/general_routes.js
  src/views/partials/_navbar.ejs
Labels: Activity completed 📄

#194 us 29 FTPS
  docs/Services/FTPS/ftpsconfig.conf
Labels: User story completed 📖, SPRINT 2

#198 Us15refunds
  src/controllers/employee_controller.js
  src/database/SQL/query_procedures.sql
  src/public/scripts/search_order.js
  src/routes/employee.js
  src/views/employees/refunds.ejs
Labels: User story completed 📖, SPRINT 3

#197 POSTFIX AND DOVECOT FILES
  docs/Services/MAIL/DOVECOT/conf.d/10-auth.conf
  docs/Services/MAIL/DOVECOT/conf.d/10-mail.conf
  docs/Services/MAIL/DOVECOT/conf.d/10-master.conf
  docs/Services/MAIL/DOVECOT/dovecot.conf
  docs/Services/MAIL/POSTFIX/main.cf
  docs/Services/MAIL/POSTFIX/master.cf
Labels: User story completed 📖, Activity completed 📄

#195 HTTPS Conf file
  docs/Services/HTTPS/nginx.conf
Labels: User story completed 📖, Activity completed 📄

#199 US-47
  src/controllers/admin_controller.js
  src/database/SQL/query_procedures.sql
  src/routes/admin.js
  src/views/admin/inventory_select_existing_accessory.ejs
Labels: User story completed 📖, Activity completed 📄

#200 Fix forms ENTER key problem
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/views/admin/existing_accesory_modify.ejs
  src/views/admin/existing_accessory.ejs
  src/views/admin/existing_accounts_state.ejs
  src/views/admin/new_accessory.ejs
  src/views/auth/create_acc_admin.ejs
  src/views/auth/login.ejs
  src/views/auth/signup.ejs
  src/views/auth/signup_business.ejs
  src/views/contact_us.ejs
  src/views/employees/refunds.ejs
  src/views/shop/employee_shopping_cart.ejs
  src/views/userUpdate.ejs
Labels: bug 🐛

#201 Styling solf out accessories
  src/database/SQL/query_procedures.sql
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/views/admin/inventory_select_existing_accessory.ejs
  src/views/index.ejs
  src/views/products.ejs
Labels: Improvement 📈

#203 US-09 completada
  src/controllers/user_controllers.js
  src/public/scripts/recieved.js
  src/routes/user.js
  src/views/clients/orders_clients.ejs
Labels: User story completed 📖, Activity completed 📄, SPRINT 3

#205 Update bill
  .eslintrc.json
  package-lock.json
  package.json
  src/controllers/user_controllers.js
  src/database/SQL/query_views.sql
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/public/styles/main.scss
  src/public/styles/pages/_bill.scss
  src/views/shop/bill.ejs
Labels: User story completed 📖, Activity completed 📄, Improvement 📈, SPRINT 3

#204 US 20 Detalles Financieros
  src/controllers/admin_controller.js
  src/database/SQL/query_procedures.sql
  src/database/SQL/query_views.sql
  src/public/images/finances_outgoings.jpg
  src/public/images/finances_profits.jpg
  src/routes/admin.js
  src/views/admin/finances_outgoings.ejs
  src/views/admin/finances_profits.ejs
  src/views/admin/finances_select_option.ejs
  src/views/admin/finances_select_perform_details.ejs
Labels: User story completed 📖, SPRINT 3

#206 UPDATE TABLES RESPONSIVE
  src/public/styles/_mediaQueries.scss
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/views/admin/existing_accounts.ejs
  src/views/admin/inventory_select_existing_accessory.ejs
  src/views/admin/show_messages.ejs
  src/views/clients/orders_clients.ejs
  src/views/employees/employee_show_orders.ejs
  src/views/employees/existing_inventory.ejs
  src/views/partner/existing_accounts_partner.ejs
  src/views/partner/partners_inventory.ejs
  src/views/productDetails.ejs
  src/views/shop/employee_shopping_cart.ejs
  src/views/shop/shopping_cart.ejs
Labels: Improvement 📈

#207 Validacion devoluciones
  src/controllers/employee_controller.js
  src/database/SQL/query_init.sql
  src/database/SQL/query_inserts.sql
  src/database/SQL/query_procedures.sql
  src/public/styles/main.css
  src/public/styles/main.scss
  src/public/styles/pages/_finances.scss
  src/views/admin/finances_historic_prices.ejs
  src/views/admin/finances_select_perform_details.ejs
  src/views/employees/refunds.ejs
Labels: Improvement 📈

#208 Organize code
  src/controllers/admin_controller.js
  src/controllers/cart_controller.js
  src/controllers/employee_controller.js
  src/controllers/general_routes.js
  src/controllers/partner_controller.js
  src/controllers/user_controllers.js
  src/database/SQL/query_procedures.sql
  src/index.js
  src/routes/admin.js
  src/routes/cart_api.js
  src/routes/employee.js
  src/routes/general_routes.js
  src/routes/partner.js
  src/routes/router_authentication.js
  src/views/admin/admin_add_inventory_to_existing.ejs
  src/views/admin/admin_change_account_state.ejs
  src/views/admin/admin_finances_inventory.ejs
  src/views/admin/admin_finances_outgoings.ejs
  src/views/admin/admin_finances_profits.ejs
  src/views/admin/admin_finances_select_dashboard.ejs
  src/views/admin/admin_finances_select_report.ejs
  src/views/admin/admin_inventory_select_dashboard.ejs
  src/views/admin/admin_modify_accessory.ejs
  src/views/admin/admin_new_accessory.ejs
  src/views/admin/admin_price_history.ejs
  src/views/admin/admin_show_accounts.ejs
  src/views/admin/admin_show_inventory.ejs
  src/views/admin/admin_show_messages.ejs
  src/views/admin/inventory_select_existing_accessory.ejs
  src/views/auth/admin_create_account.ejs
  src/views/clients/client_show_orders.ejs
  src/views/contactUs.ejs
  src/views/employees/employee_refunds.ejs
  src/views/employees/employee_show_inventory.ejs
  src/views/home.ejs
  src/views/partials/_stateAccount.ejs
  src/views/partials/_statusAccesory.ejs
  src/views/partner/partners_show_accounts.ejs
  src/views/partner/partners_show_inventory.ejs
  src/views/shop/bill.ejs
  src/views/shop/employee_shopping_cart.ejs
  src/views/updateAccount.ejs
Labels: Improvement 📈

#209 Format fix
  src/controllers/admin_controller.js
  src/controllers/cart_controller.js
  src/controllers/controller_auth.js
  src/controllers/employee_controller.js
  src/controllers/general_routes.js
  src/controllers/partner_controller.js
  src/controllers/user_controllers.js
  src/database/SQL/query_procedures.sql
  src/database/connection.js
  src/libs/helpers.js
  src/libs/passport.js
  src/libs/protect_middlewares.js
  src/public/scripts/addSub.js
  src/public/scripts/confirm_user_account_delete.js
  src/public/scripts/navbar.js
  src/public/scripts/recieved.js
  src/public/scripts/search_order.js
  src/public/scripts/validations/validate_global.js
  src/public/styles/_mediaQueries.scss
  src/public/styles/base/_globals.scss
  src/public/styles/components/_components.scss
  src/public/styles/layouts/_nav.scss
  src/public/styles/main.scss
  src/public/styles/pages/_accessory_details.scss
  src/public/styles/pages/_bill.scss
  src/public/styles/pages/_carrito.scss
  src/public/styles/pages/_contactUs.scss
  src/public/styles/pages/_finances.scss
  src/public/styles/pages/_home.scss
  src/public/styles/pages/_inventory_select_accessory_type.scss
  src/public/styles/pages/_inventory_select_existing_accessory.scss
  src/public/styles/pages/_products.scss
  src/public/styles/pages/_signup.scss
  src/routes/admin.js
  src/routes/cart_api.js
  src/routes/partner.js
  src/routes/router.js
  src/routes/router_authentication.js
  src/routes/user.js
  src/views/admin/admin_finances_select_report.ejs
  src/views/admin/admin_modify_accessory.ejs
  src/views/admin/admin_new_accessory.ejs
  src/views/auth/admin_create_account.ejs
  src/views/auth/login.ejs
  src/views/auth/signup.ejs
  src/views/auth/signup_business.ejs
  src/views/contactUs.ejs
  src/views/employees/employee_refunds.ejs
  src/views/employees/employee_show_inventory.ejs
  src/views/home.ejs
  src/views/partner/partners_show_inventory.ejs
  src/views/shop/bill.ejs
  src/views/shop/employee_shopping_cart.ejs
  src/views/shop/shopping_cart.ejs
  src/views/updateAccount.ejs
Labels: bug 🐛, Improvement 📈

#211 Fix us01
  src/controllers/cart_controller.js
  src/controllers/user_controllers.js
  src/database/SQL/query_procedures.sql
  src/database/SQL/query_views.sql
  src/libs/protect_middlewares.js
  src/routes/cart_api.js
  src/routes/user.js
  src/views/contactUs.ejs
  src/views/home.ejs
  src/views/partials/_navbar.ejs
  src/views/productDetails.ejs
  src/views/products.ejs
Labels: bug 🐛

#212 3️⃣ FIXES SPRINT NÚMERO 3
  src/controllers/cart_controller.js
  src/controllers/user_controllers.js
  src/database/SQL/query_procedures.sql
  src/database/SQL/query_views.sql
  src/libs/protect_middlewares.js
  src/routes/cart_api.js
  src/routes/user.js
  src/views/contactUs.ejs
  src/views/home.ejs
  src/views/partials/_navbar.ejs
  src/views/productDetails.ejs
  src/views/products.ejs
Labels: bug 🐛, Sprint completed ☑️, Improvement 📈, SPRINT 3

#215 Dev a deployment
  README.md
  docs/Diagrams/Network_topology/.gitkeep
  docs/Diagrams/Network_topology/autoupb_network_topology.png
  docs/Diagrams/Network_topology/wearcar_network_topology.pkt
  docs/Diagrams/Network_topology/wearcar_network_topology.png
  docs/Physical_infrastructure/Access_point/.gitkeep
  docs/Physical_infrastructure/Access_point/ap.xml
  docs/Physical_infrastructure/Router/router-confg
  src/database/SQL/query_procedures.sql
Labels: Sprint completed ☑️, SPRINT 3
